export const items = [
    {
        id: 'Joico',
        title: 'Daily Care',
        author: 'Joico Hair',
        cover: 'joico.png',
        price: 3,
        onSale: true,
    },
    {
        id: 'Matrix',
        title: 'Matrix Biolage Color',
        author: 'Biolage',
        cover: 'matrix.png',
        price: 4,
        onSale: true,
    },
    {
        id: 'Pravana',
        title: 'Perfect Blonde',
        author: 'Pravana Hair Cair',
        cover: 'pravana.png',
        price: 2,
        onSale: false,
    },
    {
        id: 'Chi',
        title: 'Silk Infusion Reconstructing Complex',
        author: 'faruq',
        cover: 'chi.png',
        price: 4,
        onSale: true,
    },
    {
        id: 'Tigi',
        title: 'Rehab For Hair',
        author: 'Bead Head Hair',
        cover: 'tigi.png',
        price: 2,
        onSale: false,
    },
];